#+title: Readme

* Guild Living Campaign

These are my notes playing with [[https://app.roll20.net/lfg/listing/17445/guild-living-campaign][Guild Living Campaign]] on Roll20. For the last 7+
years, The Guild Living Campaign has been the largest, most active D&D 4e
campaign on roll20, and now you have a chance to join in on the adventure.

Here's the basic idea for this campaign: It is open to all players, including
new players, with no specific limit on the number of total players. Each
session, the players will roll d20 and the top 5 or 6 rolls will get into the
party for that day; players that don't make it in have an increased chance of
getting into the next session they want to play.

** My Characters
- [[file:brodush.org][Brodush]] Level 5 Half-Orc Ranger Archer

** Play Sessions
- [[file:2024-08-03-session.org][2024-08-03]]: First play session. The Guild is hired to investigate a local
  temple that has been problematic lately. A priest, Lathandarius, thought he
  and an assistant could handle it. They haven't been heard from in several
  days. When we got there, we were attacked by his assistant, Jorian, and a mob
  of zealot minnions. We killed the zealots and managed to knock Jorian
  unconscious. Further into the temple we were attacked by Lathandarius and
  another mob of zealots and undead. We managed to also knock him unconscious
  rather than killing. We went down into a pit and found the Scourge of
  Baphomet. While not _The_ Scourge of Baphomet, it was a giant, undead monster
  that presumed his title. It was an intense battle, but we killed him. As it
  turns out he was controlling Lathandarius and Jorian's minds. Once the Scourge
  was defeated, both came into their right mind with no memory of the previous
  days' events.
- [[file:2024-08-17.org][2024-08-17]]: Second play session. The Guild was hired to restore order to a
  local prison. A day or so ago, the prisoners riot and take control of the
  prison capturing several guards. Almost all of the prisoners were petty
  criminals with relatively short sentences. The warden doesn't understand why
  they rioted. His request is that we rescue the guards, restore order, and
  return the prisoners to the cells (that we can). After briefly attempting to
  negotiate with the prisoners, we storm in. The first room has quite a few
  prisoners that we subdue fairly quickly. The second area has fewer prisoners,
  and we're able to free the guards. They tell us of a new prisoner that was
  admitted recently and things changed. He has white eyes and pale skin, but
  isn't a drow. We press on and find a halway with two doors. We break into the
  first door and find Lianthorn, the prisoner in question. About mid-way through
  the battle, we're able to discern Lianthorn has mind control over the entire
  prison forcing them to fight. After a few intense rounds, the other door opens
  and more prisoners pour out. Almost overrun, several of us lay unconscious on
  the floor. We finally are able to kill Lianthorn. Doing so releases the mind
  control over the prisoners and they stop fighting. This was a close one, but
  we managed to finish the mission.
- [[file:2024-08-24.org][2024-08-24]]: The Guild was hired to retreive stolen properties. Jorildyn
  Eyninoar is an Eladrin Merchant in the city of Luskan. We were able to portal
  to the city and ascertain a small group of soldiers had come through the gates
  badly wounded and bloodied. They went into the Merchant's district. Upon
  finding Mr Eyninoar's home, he informed us that they were shipping magical
  weapons and items into Luskan in preparation for the war with the Drow. The
  shipping caravan was ambushed, almost all of the guards were killed, and the
  items were stolen. Mr. Eyninoar hired us to retreive the stolen items and
  punish the "Darkies" who perpetrated this ambush. Using the map he provided,
  we were able to easily find the location of the ambush and tracked very large
  prints through the forest. Unfortunately, we stumbled upon a group of trolls
  along the way. We killed two large trolls and a brood of smaller ones.
  Continuing to follow the tracks, we came upon an encampment of Goliaths.
  Without hessitation, we initiated combat. We briefly had sight on a Drow in
  the camp, but he fled into a tower and then portaled out. After killing most
  of the goliath crew and subduing the others, we were able to find most of the
  items of the manifest except for a single amulet. Presumably the Drow took it
  with him. Mr. Eyninoar was most displeased we let the Drow escape with the
  amulet, but was happy enough to get the rest of the items returned.
- [[file:2024-09-21.org][2024-09-21]]: The Guild was hired to guard merchandise on an airship. We faught
  a band of cat-humaniod pirates. It was definitely exciting fighting on the
  deck of an airship. Several of the pirates road flying Skinwing Behemoths. We
  managed to subdue many of them, including their Captain Hera. There was a
  discussion about retaliating and trying to capture the pirate airship, but the
  captain of our vessel was dead-set against it. So we pressed on to make our
  delivery. Shortly thereafter, we were encased in a wild storm from which an
  abyssal maw attacked us. We were pretty spent after fighting the pirates and
  didn't have alot of energy left for some of our stronger attacks. The maw had
  tendrils that wrapped around the ship and would grab us. Also, there were
  elemental firestarters and gremlins that were directly trying to destroy the
  ship itself. It was a pretty long fight, but we managed to repell the maw and
  continue on our journey. Once we reached the destination, we turned over the
  subdued pirates to the local authority and then returned home.
